### ISSUE TITLE
link readme 404

### ISSUE THREAD

**Issue by ElDavoo** [Truelite/python-a38#12]
Ciao, il link nel readme non esiste più

**Comment by spanezz** [comment]
Triaging: il link che non funziona è <https://www.fatturapa.gov.it/export/fatturazione/it/normativa/f-2.htm> e conteneva gli esempi di file `.xml` forniti da fatturapa.

**Comment by spanezz** [comment]
Ora sembra essere su https://www.fatturapa.gov.it/it/lafatturapa/esempi/
