### ISSUE TITLE
a38tool: fails with "unexpected keyword argument 'required'"

### ISSUE THREAD

**Issue by angus73** [Truelite/python-a38#13]
a38tool fails with an uncaught exception:

$ a38tool --help
uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/a38-0.1.3-py3.6.egg/EGG-INFO/scripts/a38tool", line 360, in <module>
  File "/usr/local/lib/python3.6/dist-packages/a38-0.1.3-py3.6.egg/EGG-INFO/scripts/a38tool", line 330, in main
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

Am I missing something?

**Comment by spanezz** [comment]
It looks like you're using an old version of Python3 that a38 is not supporting: the `required` argument to [add_subparsers](https://docs.python.org/3.8/library/argparse.html#argparse.ArgumentParser.add_subparsers) has been added in Python 3.7:
> required - Whether or not a subcommand must be provided, by default False (added in 3.7)

Note that Python 3.6 is [end-of-life as of 2021-12-23](https://www.python.org/dev/peps/pep-0494/#lifespan).

**Comment by angus73** [comment]
Many thanks, I had Python 3.6 indeed.
Now I have just installed Python 3.7 using the deadsnakes PPA (as described [here](https://linuxize.com/post/how-to-install-python-3-7-on-ubuntu-18-04), but the problem is still there. More info:

$ python --version
Python 2.7.17

$ python3.7 --version
Python 3.7.12

I can guess there is some kind of binding to do, I tried to alias "python" to "python3.7" but still doesn't work, so (obviously), as I am not an expert, I think I would need some more help. Let me know if you can kindly help me, or maybe where I can ask.

Many thanks, again
(running Ubuntu 18.04)

**Comment by spanezz** [comment]
Hello. The only thing I can think of is to replace the first line of a38tool to point to `python3.7` instead of `python3`

**Comment by angus73** [comment]
Thank you!
Did it, and it seems something is movin' on, but now:

$ a38tool --help
Traceback (most recent call last):
  File "/home/andrea/.local/bin/a38tool", line 9, in <module>
    import a38.fattura as a38
ModuleNotFoundError: No module named 'a38'

My previous step was "pip3 install a38", was it correct or is there a better way?

Thanks again

**Comment by spanezz** [comment]
This has become something not so relevant to a38's code and more relevant to assistance with local system setup. At a38 level, I cannot do much more than documenting the requirements.

I'm closing the ticket
