### ISSUE TITLE
Run tests as Github actions

### ISSUE THREAD

**Issue by tappoz** [Truelite/python-a38#14]
Hello, thank you for this very useful project!
Would you consider Pull Requests adding Github Actions to automatically run tests with a badge to monitor the outcome?

**Comment by spanezz** [comment]
Yes please, great idea!

**Comment by tappoz** [comment]
:ok: I can implement this, and get back here with the details. Thanks again for this useful project :pray:

**Comment by tappoz** [comment]
This is the PR: https://github.com/Truelite/python-a38/pull/15
Unfortunately I am unable to run the workflow on Github until it gets merged. See the PR description for more details.

**Comment by spanezz** [comment]
Thank you! @valholl merged it and it works! I just fixed the badge link in the README. We have a CI, weeee!
