### ISSUE TITLE
Add linters, static code analysis and vulnerability checkers

### ISSUE THREAD

**Issue by tappoz** [Truelite/python-a38#16]
Hello, another useful thing would be to add a variety of Pip packages that help in making the source code looking the same regardless the project and check things like PEP8, static code analysis, type checkers and vulnerability checkers. 

There's a variety of Pip projects that cover the topics above, would you be interested in a Pull Request to add all these tools and checks? It would come handy in the CI pipeline as well.

**Comment by valholl** [comment]
It would be pretty interesting, thanks!

**Comment by tappoz** [comment]
See the comments on the PR link. Thanks :pray:
