### ISSUE TITLE
Invoice with natura=N2.1 (VAT "non soggette ad imposta") 

### ISSUE THREAD

**Issue by tappoz** [Truelite/python-a38#18]
As per here (or similar docs from AdE): https://www.agenziaentrate.gov.it/portale/documents/20143/451259/Guida_compilazione-FE_25+11+20.pdf/e811fe3d-332d-5b51-5990-10d7e4641164

There's this new value for the "natura" field: N2.1 (and N2.2 as well actually).

> N2.1 – Operazioni non soggette ad IVA ai sensi degli artt. da 7 a 7-septies del d.P.R. n.
633/72

If I validate a XML fattura file containing N2.1 (that passed the AdE SDI validation), then I see this:

```
fattura_elettronica_body.0.dati_beni_servizi.dettaglio_linee.0.natura: 'N2.1' is not a valid choice for this field
fattura_elettronica_body.0.dati_beni_servizi.dettaglio_linee.0.natura: 'N2.1' should be no more than 2 characters long
...
fattura_elettronica_body.0.dati_beni_servizi.dati_riepilogo.0.natura: 'N2.1' is not a valid choice for this field
fattura_elettronica_body.0.dati_beni_servizi.dati_riepilogo.0.natura: 'N2.1' should be no more than 2 characters long
```

I checked the code base and found a few places where these new strings could be added:

```
$ grep -nrIi '"N2"' <<...>>/site-packages/a38/
<<...>>/site-packages/a38/fattura_semplificata.py:95:    natura = fields.StringField(length=2, null=True, choices=("N1", "N2", "N3", "N4", "N5", "N6", "N7"))
<<...>>/site-packages/a38/fattura.py:280:    natura = fields.StringField(length=2, choices=("N1", "N2", "N3", "N4", "N5", "N6", "N7"), null=True)
<<...>>/site-packages/a38/fattura.py:357:    natura = fields.StringField(length=2, null=True, choices=("N1", "N2", "N3", "N4", "N5", "N6", "N7"))
<<...>>/site-packages/a38/fattura.py:377:    natura = fields.StringField(length=2, null=True, choices=("N1", "N2", "N3", "N4", "N5", "N6", "N7"))
```

Is there anything else that should be amended? I could provide a PR if that's fine. Thanks :pray:

**Comment by spanezz** [comment]
Good catch, the list of choices need updating, and it looks like you caught them all. It looks like it's a good opportunity to deduplicate those lists into a constant tuple to reuse in `choices=`. Perhaps adding `a38/consts.py`?

Looking at the AdE docs, `tipo_documento` also has an incomplete set of choices and could use the same treatment.

I wish AdE could provide static links to standards so one could link to them from code comments, but I guess times are not ready for that.

A PR is always appreciated! ❤️

**Comment by tappoz** [comment]
OK - will try to give this a go in a PR :crossed_fingers: :pray:

**Comment by spanezz** [comment]
Thank you! The definition of fatture really needed this kind of refactoring!
