### ISSUE TITLE
Aggiunta riga di dettaglio con aliquota iva a 0 e codice natura

### ISSUE THREAD

**Issue by raulidavide** [Truelite/python-a38#27]
Buongiorno , premetto che sto usando la vostra procedura per generare la fattura elettronica da un database sql e la trovo fantastica, ho un solo problema, se genero la fattura con i codici iva non ci sono problemi e questa è la riga che uso per aggiungere i dettagli:

body.dati_beni_servizi.add_dettaglio_linee(
    descrizione="Test item", quantita=2, unita_misura="kg",
    prezzo_unitario="25.50", aliquota_iva="22.00")

anche controllando l'xml me lo da corretto 

mentre se metto l'aliquota iva a "0"  indicando la natura:

body.dati_beni_servizi.add_dettaglio_linee(
    descrizione="Other item", quantita=1, unita_misura="kg",
    prezzo_unitario="15.50", aliquota_iva="0.00", natura="N3.1")

mi da questo errore :
fattura_elettronica_body.0.dati_beni_servizi.natura: [00429] field is empty while aliquota_iva is zero

e anche da controllo formale me la scarta

potete gentilmente dirmi dove sto sbagliando?

**Comment by spanezz** [comment]
Ho finalmente implementato la gestione di `natura` nella generazione di `dettaglio_linee`: ora dovrebbe calcolare il dettaglio correttamente senza bisogno di correzioni aggiuntive
