### ISSUE TITLE
Missing ability to list / extract attachments

### ISSUE THREAD

**Issue by paride** [Truelite/python-a38#32]
Sometimes _fatture elettroniche_ have attachments, e.g.
```
[...]
    <Allegati>
      <NomeAttachment>someattachment.pdf</NomeAttachment>
      <DescrizioneAttachment>attachment description</DescrizioneAttachment>
      <Attachment>[encoded data]</Attachment>
    </Allegati>
  </FatturaElettronicaBody>
</ns2:FatturaElettronica>
```
It would be useful to list and extract them with a38.

**Comment by spanezz** [comment]
It would! The library already supports doing it, here's some example code to do it:

```py
        # Save attachments
        for body in fattura.fattura_elettronica_body:
            for allegato in body.allegati:
                with open(allegato.nome_attachment, "wb") as fd:
                    fd.write(allegato.attachment)
```

It would indeed be useful to have this in `a38tool`. Could you help me with the design on how it should work? I'll dump random thoughts to kickstart a discussion.

Each `xml` file can contain an arbitrary number of attachments, each with an arbitrary file name. Just extracting them as they are could mean clobbering existing files in the current directory, but maybe it's ok, and not that different from unzipping a .zip file without looking inside?

Could an `a38tool`  subcommand with a subset of `unzip`'s command line options be a workable approach?

In case of multiple attachments with the same name, would adding a ` (1)` suffix before the extension to remove ambiguity, like a web browser download, be ok?

**Comment by paride** [comment]
Hi @spanezz! This is a (possibly flawed) brain-dump on how I imagine it.

I imagine is having two a38tool subcommands:
```
    attachment-list
    attachment-extract [-f] [-o OUTPUT] <ID>
```
where `attachment-list` lists attachments giving them an ID (progressive integer). Mockup:
```
[1] one-attachment.pdf
    attachment description
[2] another attachment.pdf
    another description
```
The ID can be passed to `attachment-extract` to extract a specific attachment. The optional arguments `[-f]` and `[-o OUTPUT]` have the same behavior they have with the `pdf` subcommand. This way we leave the "attachments with same name" problem to the user (hopefully this doesn't happen that often)

(Maybe: make `<ID>` optional and if not specified `attachment-extract` extracts all the attachments, failing if a file has to be overwritten unless `-f` is specified. The `-o` option requires `ID` to be specified.)

I think it's OK to clobber the current directory (same as `unzip` does).

**Comment by spanezz** [comment]
I pushed a prototype in the branch `issue32`. Would you like to have a look?

This is the interface I put together:

```
$ ./a38tool allegati --help
usage: a38tool allegati [-h] [--extract] [--json] [--yaml] [--output OUTPUT] file [attachments ...]

positional arguments:
  file                  input file (.xml or .xml.p7m)
  attachments           IDs or names of attachments to extract. Shell-like wildcards allowed

options:
  -h, --help            show this help message and exit
  --extract, -x         extract selected attachments
  --json                show attachments in json format
  --yaml                show attachments in yaml format
  --output OUTPUT, -o OUTPUT
                        destination file name (-o file) or directory (-o dir/)
```

It can:

* list attachments in human readable (default), json, yaml
* filter attachments by ID or by file name (globs allowed)
* extract to the current directory, overwriting files with the same name if any
* extract to a given directory (`-o existing_dir`, -o `new_dir/`) or to a given file (`-o file` when only one output is selected)

`--output` is kind of DWIM, and should match what `cp` is doing with its destination argument, plus creating the output directory if it does not exist.

**Comment by paride** [comment]
@spanezz looks good! Some comments:

- I kind of expected to be able to pass the list of attachments to extract as a `-x` argument, e.g. `a38tool allegati -x 01 fattura.xml`, as `tar` allows this syntax. I would prefer this way from the UX point of view, but the way you implemented it is also fine, and the tool works as documented.
- It is easy to make a38tool traceback if the arguments are wrong. However the tool does little input validation in general (e.g. `a38tool json xx.xml` => traceback). If this is a design decision I think it's fine.
- The tool doesn't warn if a nonexisting attachment is requested (`a38tool allegati -x fattura.pdf nonexistent`). Not a bug, the behavior is consistent, just an observation.
- What happens if an attachment name conflicts with an attachment it?
- Looks like in my fatture the attachment format is not defined, and I end up with an ugly `None` in the attachment list:
```
01: None someattachment.pdf
    Foo bar description
```

**Comment by spanezz** [comment]
Hi!

* I was surprised that `a38tool allegati -x '01 fattura.xml'` isn't working: it looks more like a quirk of python's argparse than a design choice, and I'm not sure it's worth the time to investigate to match tar's behaviour (tar's command line is rather tricky in its own right)
* It's not really a design decision to make a38tool traceback if the arguments are wrong: it's more that a38tool was mostly a demo of the library functions and has never really been polished as a front-end. PRs welcome, though
* If an attachment name is completely numeric, it is currently parsed as an attachment ID and not as a glob. Should I add a feature so that if the attachment name begins with `^` it is treated like a regexp, so one could do `^01$` to match an attachment filename of exactly `"01"`?
* I pushed a change that uses `-` instead of None as the format if `formato_attachment` is not defined

What do you think? Shall I merge?

**Comment by paride** [comment]
Hi @spanezz, thanks for resurrecting this discussion! The regexp idea is nice, as it allows to keep the syntax simple while allowing a stricter mode if needed. However I don't think that's critical (I don't expect all-numeric attachments to be common, and one can still play tricks with globs if needed I believe).

+1 for the other changes.
