### ISSUE TITLE
support of wkhtmltopdf, 0.12.6 - Warning: Blocked access to file

### ISSUE THREAD

**Issue by ralcini** [Truelite/python-a38#6]
wkhtmltopdf version 0.12.6 blocks by default the local access to file.
It's needed to to add the option --enable-local-file-access to have a successfull transformation of html file to pdf

https://github.com/Truelite/python-a38/blob/5027fad9d87bd31935ae8d1d2baa536f4bcb881f/a38/render.py#L36

can be changed in

`res = subprocess.run([wkhtmltopdf, "--enable-local-file-access", fd.name, output_file], stdin=subprocess.DEVNULL, capture_output=True)`

**Comment by spanezz** [comment]
Adding `--enable-local-file-access` sounds good to me: it's what it needs to do after all.

It might be a bit trickier to figure out when to pass that option and when not to, as earlier versions of `wkhtmltopdf` don't seem to support it.

I guess, in the worst case, we can look at `wkhtmltopdf --version` or parse `wkhtmltopdf --help` to see if the option is mentioned

**Comment by spanezz** [comment]
Thank you for the pull request! I've merged it and documented the situation in the code with a link to this issue
