### ISSUE TITLE
Run transformation on Windows machine

### ISSUE THREAD

**Issue by ralcini** [Truelite/python-a38#7]
Under Windows 10 I detect an issue in the way you generate the temporary html file to transformed. In particular, the temporary file is not closed and the wkhtmltopdf process cannot access to it for reading.

https://github.com/Truelite/python-a38/blob/5027fad9d87bd31935ae8d1d2baa536f4bcb881f/a38/render.py#L33

Exception 

`RuntimeError: ('%s exited with error %d: stderr: %s', 'C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.EXE', 1, b'Loading pages (1/6)\r\n[>                                                           ] 0%\r[======>                                                     ] 10%\rError: Failed to load file:///C:/Users/xxxxxxx/AppData/Local/Temp/tmpx8xa1dir.html, with network status code 201 and http status code 0 - Error opening C:/Users/xxxxxxx/AppData/Local/Temp/tmpx8xa1dir.html: Impossibile accedere al file. Il file \xe8 utilizzato da un altro processo.\r\nError: Failed loading page file:///C:.....`

My personal quick fix, but it's needed a better error handling:

```
fd = tempfile.NamedTemporaryFile("wb", suffix=".html", delete = False)
html.write(fd)
fd.flush()
name = fd.name
fd.close()
            
res = subprocess.run([wkhtmltopdf, name, output_file], stdin=subprocess.DEVNULL, capture_output=True)
os.remove(name)
```

**Comment by spanezz** [comment]
The fix looks good! If it works for you, I can merge it in with the appropriate error handling

**Comment by spanezz** [comment]
Thank you for the pull request! I've added a try/finally to make sure the tempfile is always deleted, and I guess with that this issue should be fixed
